# Generated by Django 4.2.15 on 2024-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_product_available_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default-slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="default-slug"),
        ),
    ]
