# Generated by Django 4.2.15 on 2024-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
    ]
