# Generated by Django 4.2.15 on 2024-08-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
