# Generated by Django 4.2.15 on 2024-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_category_slug_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
    ]
